name: 'Terraform'
on:
  push:
  workflow_dispatch:  
permissions:
  id-token: write
  contents: write 
jobs:
  terraform:
    uses: fiap-5soat-grupo22/workflows-templates/.github/workflows/terraform.yml@main
    with:
      tenant: ${{ fromJSON(vars.HACKATHON).tenant }}
      config: ${{ toJSON(fromJSON(vars.HACKATHON).production) }}